// Source of truth: 🧴 Products list + 🌳 Shared Environment (ClickUp, Keystone workspace)
import { IMG } from "./images";
const img = (n) => IMG[n];

export const CATEGORIES = [
  "First Aid", "Wound Care", "Medication", "Muscle & Joint", "Skin / Coat",
  "Hoof Care", "Fly / Pest Control", "Bathing", "Grooming", "Supplement", "Feed", "Dewormer",
];

export const CAT_COLOR = {
  "First Aid": "#A31E22",
  "Wound Care": "#8C3A16",
  "Medication": "#5B3E7A",
  "Muscle & Joint": "#1A5C62",
  "Skin / Coat": "#8F4D0F",
  "Hoof Care": "#5A4632",
  "Fly / Pest Control": "#3F6B45",
  "Bathing": "#2A6280",
  "Grooming": "#6B5C1E",
  "Supplement": "#5A6822",
  "Feed": "#78590E",
  "Dewormer": "#7C450C",
};

export const VERDICT = {
  "Barn Favorite": { icon: "★", label: "Barn Favorite", blurb: "Staff reach for this without thinking", tone: "gold" },
  "Proven": { icon: "✓", label: "Proven", blurb: "Reliably works, no drama", tone: "green" },
  "Does the Job": { icon: "•", label: "Does the Job", blurb: "Fine, not exciting", tone: "steel" },
  "Hit or Miss": { icon: "~", label: "Hit or Miss", blurb: "Works for some horses, not others", tone: "amber" },
  "Underwhelming": { icon: "↓", label: "Underwhelming", blurb: "We have better options", tone: "grey" },
  "Testing": { icon: "⚗", label: "Testing", blurb: "Active experiment, no verdict yet", tone: "violet" },
};

export const LOCATIONS = [
  "Med Shelf (Feed Room)", "Supplement Shelf (Feed Room)", "Overflow Shelf (Feed Room)",
  "Feed Room", "Grooming Bay", "Wash Bay",
];

// ---------------------------------------------------------------- products
export const PRODUCTS = [
  // ---- First aid / wound care
  { n: "Vetericyn Plus Wound & Skin Care Spray", c: "Wound Care", v: "Does the Job", loc: "Grooming Bay", img: img(278),
    d: "Cleans and treats minor cuts, scrapes, and skin irritation. Safe around the eyes, no rinsing.",
    dose: "Spray directly on the area 1–2× daily until healed.", sx: ["Minor cut or scrape"] },
  { n: "Vetericyn Plus Antimicrobial Hydrogel", c: "Wound Care", loc: "Grooming Bay",
    d: "Clinging hydrogel version for wounds that need coverage that stays put.", sx: ["Minor cut or scrape"] },
  { n: "Wound Ender", c: "Wound Care", v: "Proven", loc: "Grooming Bay", img: img(290),
    d: "Rash, cut, and wound treatment. Colorless, odorless, non-toxic, does not sting.",
    dose: "Apply to clean wound or skin. Wait 30 seconds before turning back out.", sx: ["Minor cut or scrape"] },
  { n: "Silver Sulfadiazine Cream 1% (Ascend)", c: "First Aid", v: "Barn Favorite", img: img(305), rx: true,
    d: "Prescription topical antibiotic cream. The one for serious infections and second- to third-degree burns.",
    dose: "Apply topically per vet. 400g jar, ~$51.54.", note: "Ordered through Stillwater Vet Clinic pharmacy.",
    sx: ["Minor cut or scrape", "Tiny Bumps From Bug Bites"] },
  { n: "Vetrap Bandaging Tape", c: "First Aid", v: "Barn Favorite", loc: "Grooming Bay", img: img(281),
    d: "Self-adherent wrap for securing bandages and supporting wounds or joints.",
    dose: "Snug, not tight, over gauze or padding. Check for swelling or heat after wrapping." },
  { n: "AluShield Aerosol Bandage (Ideal/Neogen)", c: "Wound Care",
    d: "Sprayable aluminum bandage. Seals a wound where a wrap won't stay.", sx: ["Minor cut or scrape"] },
  { n: "Farnam Tri-Care Triple Action Wound Treatment", c: "Wound Care",
    d: "Triple-action wound spray: kills bacteria, repels flies, aids healing.", sx: ["Minor cut or scrape"] },
  { n: "Farnam Wonder Dust", c: "Wound Care",
    d: "Drying wound powder for proud flesh and stubborn granulation.", sx: ["Minor cut or scrape"] },
  { n: "Corona Multi-Purpose Ointment (Manna Pro)", c: "Wound Care",
    d: "Lanolin ointment for chapped, scraped, or cracked skin.", sx: ["Minor cut or scrape"] },
  { n: "VetOne Chlorhexidine 2% Ointment", c: "Wound Care",
    d: "Antiseptic ointment for cuts and skin infections.", sx: ["Minor cut or scrape", "Rain Rot / Skin Infection"] },
  { n: "Betadine Solution (Povidone-Iodine)", c: "First Aid",
    d: "The barn workhorse antiseptic. Wound scrubs and hoof soaks.", sx: ["Minor cut or scrape", "Thrush"] },
  { n: "Triodine-7 (Priority Care)", c: "First Aid",
    d: "7% iodine solution. Stronger antiseptic for hooves and wound flushing.", sx: ["Minor cut or scrape", "Thrush"] },
  { n: "Durvet Chlorhexidine Solution 2%", c: "First Aid",
    d: "Dilutable antiseptic scrub for wounds and rain rot.", sx: ["Minor cut or scrape", "Rain Rot / Skin Infection"] },

  // ---- Medication
  { n: "Banamine (Flunixin Meglumine) Paste", c: "Medication", v: "Barn Favorite", loc: "Med Shelf (Feed Room)", img: img(282), rx: true,
    d: "NSAID oral analgesic. The colic drug. Also fever and musculoskeletal pain.",
    dose: "0.5 mg per lb body weight once daily, per vet. Tube marked in 250 lb increments.",
    note: "Works within ~2 hrs, effective 24–36 hrs. ~$32.99.", sx: ["Colic"] },
  { n: "Bute Paste (Phenylbutazone)", c: "Medication", v: "Proven", loc: "Med Shelf (Feed Room)", img: img(311), rx: true,
    d: "NSAID paste for musculoskeletal pain and inflammation.",
    dose: "1–2 g per 500 lb daily, max 4 g/day. Each 3 mL mark = 1 g.",
    sx: ["Joint Swelling", "Swelling From Kick", "Sore Hooves"] },
  { n: "Bute Tablets (Phenylbutazone)", c: "Medication", v: "Barn Favorite", loc: "Med Shelf (Feed Room)", img: img(312), rx: true,
    d: "1 g tablets. Easier to dose precisely than the paste.",
    dose: "1–2 tablets per 500 lb, max 4 g/day. Higher dose first 48 hrs, then maintenance. ~$0.50/tablet.", sx: ["Sore Hooves"] },
  { n: "Equioxx (Firocoxib) Tablets", c: "Medication", v: "Hit or Miss", loc: "Med Shelf (Feed Room)", img: img(313), rx: true,
    d: "FDA-approved NSAID for osteoarthritis. More selective than bute, lower GI and kidney risk.",
    dose: "One 57 mg tablet daily (800–1,300 lb), up to 14 days. Can be hand-fed.",
    note: "Add-on for flare-ups only. Adequan + Legend are the base joint program, not this.",
    sx: ["Joint Swelling", "Sore Muscles Joints"] },
  { n: "Cetirizine Hydrochloride 10mg", c: "Medication", v: "Hit or Miss", loc: "Med Shelf (Feed Room)", img: IMG["cetirizine"],
    d: "First-line antihistamine for itch, hives, and seasonal allergies. No laminitis risk, so it's safe to use preventively.",
    dose: "10 tablets twice daily for at least 14 days. If it's working, try 15 tablets once daily.",
    note: "Start at the FIRST sign of itchiness in spring, not once a horse is miserable. Same family as Hydroxyzine: if one isn't working for a horse, switch to the other. Dr. Erin Wilson (7/18/26): antihistamines first, specifically to minimize systemic steroid exposure across the herd.",
    sx: ["Itchy"] },
  { n: "Hydroxyzine Hydrochloride 50mg", c: "Medication", v: "Does the Job", loc: "Med Shelf (Feed Room)", rx: true,
    d: "Antihistamine with a mild sedative effect. The alternate to Cetirizine.",
    dose: "10 tablets twice daily for at least 14 days. If working, try 15 once daily.",
    note: "Try this if Cetirizine isn't doing it for that particular horse. Start at first sign of itchiness.", sx: ["Itchy"] },
  { n: "Dex (Dexamethasone Tablets)", c: "Medication", v: "Does the Job", loc: "Med Shelf (Feed Room)", rx: true,
    d: "Oral tapered-course steroid for severe allergic and dermatologic flares.",
    dose: "Bug bite taper: Day 1–2 = 4 tabs, Day 3–4 = 3 tabs, and down. Heat stress: Day 1–2 = 4 tabs.",
    note: "Laminitis risk in metabolic horses. Try antihistamines first. Reach for this when antihistamines aren't cutting it but it isn't an emergency needing IV onset.",
    sx: ["Swelling From Bug Bites", "Tiny Bumps From Bug Bites", "Heat Stress", "Itchy"] },
  { n: "Dex (Dexamethasone Injectable)", c: "Medication", v: "Proven", loc: "Med Shelf (Feed Room)", img: img(310), rx: true,
    d: "Potent injectable corticosteroid, ~25× the anti-inflammatory potency of cortisol. Fastest onset for acute reactions.",
    dose: "IV only, per vet. Always follow with oral Cetirizine or Hydroxyzine for maintenance.",
    note: "7/16/26 — Dr. Jon chose this over Vetalog for Ulyssa because of her weight. Follow the course with antihistamines rather than repeating steroid doses.",
    sx: ["Itchy"] },
  { n: "Vetalog Parenteral (Triamcinolone Acetonide)", c: "Medication", v: "Does the Job", loc: "Med Shelf (Feed Room)", rx: true,
    d: "Injectable corticosteroid. Vet-administered only.",
    dose: "Reduced dose for metabolic horses — Avelin got 1/4 dose. Dahlia got a full dose for bug bumps.",
    note: "CAUTION: can trigger laminitis, especially in overweight or metabolic horses, and suppresses immune response. Dr. Jon uses IM Dex instead for heavier horses and is deliberately more cautious with the fjords.",
    sx: ["Itchy"], warn: true },
  { n: "Prascend (Pergolide) Tablets", c: "Medication", v: "Proven", loc: "Med Shelf (Feed Room)", img: img(314), rx: true,
    d: "Pergolide for PPID (equine Cushing's). Controls pituitary hormone overproduction.",
    dose: "Start 2 mcg/kg once daily, adjust up to 4 mcg/kg/day. Do NOT crush tablets.", sx: ["Cushings"] },
  { n: "IM Pergolide (Injectable)", c: "Medication", v: "Proven", loc: "Med Shelf (Feed Room)", img: img(315), rx: true,
    d: "Compounded injectable pergolide for PPID horses who fight oral dosing.",
    dose: "IM per compounding pharmacy formulation and schedule.",
    note: "Sourced through a compounding pharmacy (Wedgewood, BET Labs) per vet's formulation.", sx: ["Cushings"] },
  { n: "Cabergoline Injectable (BET Pharm)", c: "Medication", loc: "Med Shelf (Feed Room)", rx: true,
    d: "Long-acting dopamine agonist. Alternative PPID control when pergolide isn't tolerated.", sx: ["Cushings"] },
  { n: "Thyro-L (Levothyroxine Sodium)", c: "Medication", v: "Proven", loc: "Med Shelf (Feed Room)", img: img(308), rx: true,
    d: "Thyroid hormone powder for metabolic imbalance and insulin resistance / EMS.",
    dose: "Mix into daily grain. Stendahl 3 scoops. Ulyssa 3–4 scoops. Avelin 2 scoops.",
    note: "Second-to-last rung on the metabolic ladder. If insulin doesn't improve in about a month, next step is ertugliflozin. ~$26.95 (1 lb) to $239.95 (10 lb).",
    sx: ["Insulin Resistance"] },
  { n: "Ertugliflozin (SGLT2 Inhibitor)", c: "Medication", loc: "Med Shelf (Feed Room)", rx: true,
    d: "Makes the kidneys dump excess glucose, lowering blood glucose and insulin directly.",
    dose: "Vet-prescribed per horse.",
    note: "LAST resort for insulin dysregulation not controlled by diet, exercise, weight control, and Thyro-L. Insulin 200+ means laminitis is imminent. Flagged as a possible next step for Ulyssa and Avelin if the Thyro-L increase doesn't work. Not the same drug as human Ozempic despite the nickname.",
    sx: ["Insulin Resistance"], warn: true },
  { n: "Adequan (PSGAG)", c: "Medication", v: "Barn Favorite", loc: "Med Shelf (Feed Room)", rx: true,
    d: "IM joint injection that actually rebuilds cartilage. First-line ongoing joint therapy alongside Legend.",
    dose: "Loading: 1 injection every 4 days for a month (7 doses). Repeat ~2×/year. Can give at home.",
    note: "~$400 per loading-dose box. Currently on Tammy, Ulyssa, and Mickey plus monthly IV Legend. Switch to Zycosan if a horse isn't responding.",
    sx: ["Joint Swelling", "Sore Muscles Joints"] },
  { n: "Legend (Hyaluronic Acid)", c: "Medication", v: "Does the Job", loc: "Med Shelf (Feed Room)", rx: true,
    d: "Joint injection targeting synovitis (joint-fluid inflammation). Used with Adequan or Zycosan, never alone.",
    dose: "IV/IM, monthly. Currently on Tammy, Ulyssa, Mickey.", sx: ["Joint Swelling", "Sore Muscles Joints"] },
  { n: "Zycosan (Pentosan Polysulfate)", c: "Medication", loc: "Med Shelf (Feed Room)", rx: true,
    d: "IM joint injection: cartilage building blocks plus systemic anti-inflammatory. Newer to the US market.",
    dose: "Loading: 1 injection per week for a month. ~$400 per loading dose.",
    note: "Same category as Adequan, similar cost and success rate. Some horses respond better to one than the other, so switch if Adequan isn't working.",
    sx: ["Joint Swelling", "Sore Muscles Joints"] },
  { n: "Marquis / Protazil (Ponazuril / Diclazuril)", c: "Medication", loc: "Med Shelf (Feed Room)", rx: true,
    d: "FDA-approved EPM treatment. First choice for confirmed or suspected active EPM.",
    dose: "Full course per vet, based on positive or high serum antibody titer. ~$800–1,500 per course.", sx: ["EPM"] },
  { n: "Rebalance (Sulfadiazine/Pyrimethamine)", c: "Medication", loc: "Med Shelf (Feed Room)", rx: true,
    d: "FDA-approved EPM treatment. Same use as Marquis, much cheaper (older sulfa drug).",
    dose: "Per vet. Worth trying before off-label options if cost matters.", sx: ["EPM"] },
  { n: "Off-label EPM Compounds", c: "Medication", loc: "Med Shelf (Feed Room)", rx: true,
    d: "Cheaper compounded EPM route: diclazuril, decoquinate, levamisole.",
    dose: "Per prescribing vet and compounding pharmacy. Try Rebalance first.",
    note: "Reasonably safe drug class, but potency and formulation vary by compounding pharmacy.", sx: ["EPM"], warn: true },
  { n: "GastroGard (Omeprazole) Oral Paste", c: "Medication", rx: true,
    d: "Gold-standard gastric ulcer treatment. Shuts down acid production.", sx: ["Colic"] },
  { n: "DMSO Gel (Neogen)", c: "Medication",
    d: "Penetrating anti-inflammatory carrier gel for swelling and deep soreness. Wear gloves.",
    sx: ["Sore Muscles Joints", "Joint Swelling"] },

  // ---- Muscle & joint
  { n: "Bigeloil Liquid Gel", c: "Muscle & Joint", v: "Barn Favorite", loc: "Grooming Bay", img: img(320),
    d: "Menthol topical analgesic gel. Knocks down pain and swelling, also antiseptic on minor cuts.",
    dose: "Rub onto the sore area 3–4× daily. For faster relief, wrap or blanket after. 14 fl oz ~$16.99.",
    sx: ["Sore Muscles Joints", "Swelling From Kick", "Swelling From Bug Bites", "Joint Swelling"] },
  { n: "Liniment (Farnam Vetrolin)", c: "Muscle & Joint", v: "Barn Favorite", loc: "Grooming Bay",
    d: "Classic herbal liniment concentrate. Camphor, methyl salicylate, essential oils. Reduces inflammation, stimulates blood flow.",
    dose: "Body wash: 1 oz + 1 qt warm water. Brace: 4 oz + 1 qt. Full strength directly on legs for swelling.",
    note: "Different product from Vetericyn Mobility Liniment. This is the concentrate you dilute.",
    sx: ["Sore Muscles Joints", "Swelling From Kick", "Swelling From Bug Bites", "Joint Swelling"] },
  { n: "Vetericyn Mobility Liniment", c: "Muscle & Joint", loc: "Grooming Bay", img: img(321),
    d: "Fast-acting liniment with encapsulated menthol (7%) plus arnica and bisabolol.",
    dose: "Massage into the area. For deeper relief, apply under wraps. 16 oz $17.99.",
    sx: ["Swelling From Kick", "Joint Swelling", "Sore Muscles Joints", "Swelling From Bug Bites"] },
  { n: "Sore No-More Performance Ultra Poultice", c: "Muscle & Joint", v: "Proven", loc: "Grooming Bay", img: img(318),
    d: "Clinical-strength herbal poultice: bentonite clay with arnica, rosemary, witch hazel, ginger, comfrey. Draws heat and fluid out.",
    dose: "Smooth onto ankles, cannons, knees, hocks. Works as a hoof pack for abscesses. Brush off when done.",
    note: "Not for open wounds. 5 lb tub $52.99.",
    sx: ["Sore Muscles Joints", "Sore Hooves", "Hoof Abscess", "Swelling From Kick", "Swelling From Bug Bites", "Joint Swelling"] },
  { n: "Durvet Epsom Salt Poultice (Flowable Gel)", c: "Muscle & Joint", loc: "Grooming Bay", img: img(319),
    d: "Flowable gel, 60% Epsom salt with 1% methyl salicylate. Drawing agent for abscesses and bruising. No mixing.",
    dose: "Pack onto the hoof sole, or rub into sore muscles and joints. 20 oz ~$14.99.",
    sx: ["Swelling From Kick", "Sore Muscles Joints", "Hoof Abscess"] },
  { n: "Ultimate RepairV Pain Relief & Recovery Cream", c: "Muscle & Joint",
    d: "Recovery cream for sore muscles and general body work aftercare.", sx: ["Sore Muscles Joints"] },

  // ---- Hoof care
  { n: "Silvetrasol", c: "Hoof Care", v: "Barn Favorite", loc: "Grooming Bay", img: img(291),
    d: "All-natural hoof and wound wash. Thrush, white line disease, scratches, rain rot. Non-toxic, colorless, odorless.",
    dose: "Spray coronary band, hoof walls, and sole. Daily for prevention. Also cleans trimming tools. ~$21.95.",
    sx: ["Thrush", "Rain Rot / Skin Infection", "Minor cut or scrape", "Hoof Abscess"] },
  { n: "Thrush Ender (Silvetrasol)", c: "Hoof Care", v: "Proven", loc: "Grooming Bay", img: img(289),
    d: "Strongest hoof infection fighter here. Kills the bacteria, fungus, and viruses behind thrush in under 30 seconds.",
    dose: "Spray directly on frog, sole, and clefts. Safe for daily use. 16.9 oz ~$24.95.",
    note: "NOT FOR USE ON SKIN.", sx: ["Thrush"], warn: true },
  { n: "Artimud (Red Horse Products)", c: "Hoof Care", v: "Proven", loc: "Grooming Bay", img: img(293),
    d: "Clay-based antibacterial and antifungal hoof putty. Fills shallow gaps and crevices.",
    dose: "Pack into shallow open cracks. Replace every few days. Use Hoof-Stuff for deeper, narrow ones. 300g ~$22.95.",
    sx: ["Thrush"] },
  { n: "Hoof-Stuff (Red Horse Products)", c: "Hoof Care", v: "Proven", loc: "Grooming Bay", img: img(294),
    d: "Fibrous antibacterial and antifungal pack for deeper holes and cracks.",
    dose: "Flush with Sole Cleanse first. Pack fibers in with a hoof pick. Remove after 24 hrs to check. 290g ~$24.75.",
    sx: ["Thrush"] },
  { n: "Field Paste (Red Horse Products)", c: "Hoof Care", v: "Proven", loc: "Grooming Bay", img: img(292),
    d: "Conditioning frog and sole dressing for field-kept horses. Toughens tissue without being caustic.",
    dose: "Apply by gloved hand to clean, dry, wire-brushed sole and frog. Reapply weekly in mud. 750g ~$27.50.",
    sx: ["Thrush"] },

  // ---- Skin / coat
  { n: "Kinetic Vet EquiShield IBH / IR", c: "Skin / Coat", loc: "Grooming Bay",
    d: "Topical itch and skin therapy line (shampoo and spray). Topical antihistamine plus steroid plus oatmeal.",
    dose: "Apply per label alongside systemic Cetirizine or Hydroxyzine.",
    note: "Dr. Erin recommends this plus oral antihistamines before reaching for systemic steroids.", sx: ["Itchy"] },
  { n: "EquiShield IBH Spray", c: "Skin / Coat", loc: "Grooming Bay",
    d: "Medicated spray for insect bite hypersensitivity. Chlorhexidine, pramoxine, citronella, hydrocortisone.",
    dose: "Brush horse first. Spray affected or insect-prone areas. Avoid eyes. $62.04.", sx: ["Itchy"] },
  { n: "EquiShield IR (Itch Relief) Spray", c: "Skin / Coat", loc: "Grooming Bay",
    d: "Alcohol-free itch-relief spray. Pramoxine, hydrocortisone, colloidal oatmeal.",
    dose: "Shake well. Spray on skin, part the hair for contact. May use daily. $33.69.", sx: ["Itchy"] },
  { n: "EquiShield IR (Itch Relief) Shampoo", c: "Skin / Coat", loc: "Grooming Bay", exp: true,
    d: "Medicated anti-itch shampoo. Pramoxine and hydrocortisone with colloidal oatmeal and omega-6.",
    dose: "Wet coat, lather, massage, leave 5–10 min, rinse. $46.19.", sx: ["Itchy"] },
  { n: "EquiShield CK HC Spray", c: "Skin / Coat", loc: "Grooming Bay",
    d: "Medicated spray for bacterial and fungal skin infection with inflammation. Chlorhexidine, ketoconazole, hydrocortisone.",
    dose: "Clean the area, spray directly per vet. $38.94.", sx: ["Rain Rot / Skin Infection"] },
  { n: "EquiShield CK HC Salve", c: "Skin / Coat", loc: "Grooming Bay",
    d: "Same medicated formula in a thick salve base for targeted spots.",
    dose: "Clean and dry the skin, apply a thin layer. See the vet if no improvement in 2 weeks. $37.79.",
    sx: ["Rain Rot / Skin Infection"] },
  { n: "EQyss Micro-Tek Equine Spray", c: "Skin / Coat", loc: "Grooming Bay", img: img(303),
    d: "Leave-on spray that soothes red, irritated skin on contact. Instant relief from itching and rubbing.",
    dose: "Push hair aside, spray on skin, then mist coat, mane, tail. No rinse. Reapply 2–3× daily. 32 oz ~$27.99.",
    note: "Won't burn irritated skin or open wounds. Safe near girth and genital area.", sx: ["Itchy"] },
  { n: "EQyss Micro-Tek Equine Gel", c: "Skin / Coat",
    d: "Gel version for spot treatment on scabs and hot spots.", sx: ["Rain Rot / Skin Infection", "Itchy"] },
  { n: "EQyss Mega-Tek Horse Rebuilder", c: "Skin / Coat", v: "Testing", loc: "Grooming Bay", img: img(301), exp: true,
    d: "Protein-binding gel that revives dry coats and repairs cracked, brittle hooves.",
    dose: "Manes and tails: apply to wet hair, leave 5 min, rinse. Hooves: coronet band, wall, frog. 2–3× per week.",
    note: "Regrew Qu's mane fast at 2–3×/week. Live experiment on Dahlia: daily for 30 days to see if mane, forelock, and tail come in thicker.",
    sx: ["Mane/Tail"], url: "https://eqyss.com/products/eqyss-mega-tek-horse-rebuilder-repair-revitalize-strengthen-perfect-for-manes-tails-and-hooves" },
  { n: "Coat Defense", c: "Skin / Coat", v: "Hit or Miss", loc: "Grooming Bay", exp: true,
    d: "Daily preventative drying powder for skin.",
    note: "In a split-body trial against Micro-Tek on Qu.", sx: ["Itchy"] },
  { n: "Coat Defense Trouble Spot Drying Paste", c: "Skin / Coat",
    d: "Drying paste for scabby trouble spots and funk that needs pulling out.",
    sx: ["Rain Rot / Skin Infection", "Itchy"] },
  { n: "MTG (Mane Tail Groom)", c: "Skin / Coat", loc: "Grooming Bay", img: img(285),
    d: "Sulfur oil that conditions skin and pushes hair growth. Helps rain rot and dry, itchy skin. Smells like it works.",
    dose: "Apply to affected skin, mane, or tail. Leave on, wash out after a few days if you want.", sx: ["Mane/Tail"] },
  { n: "Riggin's Nu-Stock", c: "Skin / Coat",
    d: "Sulfur, pine oil, and mineral oil salve. Old-school heavy artillery for stubborn skin funk.",
    sx: ["Rain Rot / Skin Infection", "Itchy"] },
  { n: "Equiderma Zinc Oxide Paste", c: "Skin / Coat",
    d: "For pastern dermatitis: scratches, greasy heel, dew poisoning, mud fever. Sulfate free.",
    sx: ["Rain Rot / Skin Infection"] },
  { n: "Kinetic Vet EquiShield SB (SunBlock SPF 30)", c: "Skin / Coat",
    d: "SPF 30 sunblock with aloe for pink noses and bald faces. Veterinary use only." },
  { n: "Sunflower Suncoat Spray", c: "Skin / Coat",
    d: "UV protection for coats, manes, and tails against sun bleaching and burning.", sx: ["Coat"] },
  { n: "Burt's Bees Baby Dusting Powder", c: "Skin / Coat",
    d: "Cornstarch dusting powder for damp, chafing skin. Gentle enough for raw spots.", sx: ["Itchy"] },

  // ---- Fly / pest
  { n: "Charlee's Fly Spray", c: "Fly / Pest Control", v: "Barn Favorite", loc: "Grooming Bay",
    d: "All-natural, human-safe, and it actually smells nice. Resists flies, horse flies, gnats, mosquitos, ticks.",
    dose: "Shake well. Spray and wipe on.",
    note: "Carrot seed oil, lemongrass, vitamin E, MCT, peppermint. Biodegradable, pesticide-free.", sx: ["Bugs"] },
  { n: "Fly Bye! Plus Fly Spray", c: "Fly / Pest Control", v: "Barn Favorite", loc: "Grooming Bay",
    d: "Soy-based repellent for flies, mosquitoes, gnats, and ticks.",
    dose: "Spray and wipe on a DRY horse or area (doorway, wash bay).", sx: ["Bugs"] },
  { n: "Pyranha Zero-Bite Fly Spray", c: "Fly / Pest Control", v: "Barn Favorite", loc: "Grooming Bay",
    d: "All-natural. Kills and repels flies, no-see-ums, gnats, mosquitoes. Also kills fleas.",
    dose: "Ready to use, spray per label. 1 quart.", note: "Geraniol, clove oil, peppermint oil.", sx: ["Bugs"] },
  { n: "Pure Sole Bug Off Balm", c: "Fly / Pest Control", v: "Barn Favorite", loc: "Grooming Bay",
    d: "Eucalyptus-based repellent balm. Safe around nose, ears, eyes, and sore wounds.",
    dose: "Apply a thin layer to protect skin. 8 fl oz tin.", sx: ["Tiny Bumps From Bug Bites", "Bugs"] },
  { n: "SWAT Fly Repellent Ointment", c: "Fly / Pest Control", v: "Does the Job", loc: "Grooming Bay", img: img(280),
    d: "Keeps flies off wounds, eyes, and other sensitive areas.",
    dose: "Thin layer as needed, especially before turnout.", sx: ["Bugs", "Minor cut or scrape"] },
  { n: "Ultrashield EX Fly Spray", c: "Fly / Pest Control", v: "Does the Job", loc: "Grooming Bay", img: img(284),
    d: "Long-lasting fly, tick, and mosquito repellent for daily turnout.",
    dose: "Spray evenly over the body, avoiding eyes and open wounds.", sx: ["Bugs"] },
  { n: "Absorbine Ultra Shield Gold Fly Spray", c: "Fly / Pest Control", v: "Does the Job", loc: "Grooming Bay",
    d: "Kills and repels over 100 insects, and interrupts their homing system. Stops bites before they land.",
    dose: "Apply per label. 32 fl oz.", sx: ["Bugs"] },
  { n: "Absorbine Ultra Shield Green Fly Spray", c: "Fly / Pest Control", v: "Does the Job", loc: "Grooming Bay",
    d: "Natural, eco-safe repellent. Kills and repels flies, gnats, mosquitoes; repels ticks.",
    dose: "Apply per label. 1 gallon.", note: "Geraniol, clove, citronella, rosemary, lemongrass, cedarwood, thyme.", sx: ["Bugs"] },
  { n: "Bronco Gold Equine Fly Spray", c: "Fly / Pest Control", v: "Does the Job", loc: "Grooming Bay", img: img(317),
    d: "2-in-1 fly spray and coat conditioner. Citronella scent, contains lanolin.",
    dose: "Wipe on with a damp cloth against the hair, or spray as a fine mist. Max 2 oz per application, repeat daily.",
    note: "Brush out after for shine. Covers stable, horn, house, face, horse, and deer flies plus mosquitoes and gnats.", sx: ["Bugs"] },
  { n: "Equicare Flysect Super-7 Fly Spray", c: "Fly / Pest Control", v: "Does the Job", loc: "Grooming Bay", img: img(316),
    d: "Dual insecticide and repellent plus coat conditioner with aloe and lanolin. Covers gnats, mites, chiggers, fleas, ticks, lice.",
    dose: "Spray or wipe on. Daily for 2–3 days, then every 5–10 days. Reapply after washing or heavy rain.",
    note: "Brush the horse first; avoid eyes, mouth, nose.", sx: ["Bugs"] },
  { n: "Equiderma Neem & Aloe Herbal Fly Spray", c: "Fly / Pest Control", v: "Does the Job", loc: "Grooming Bay",
    d: "Plant-based herbal spray: neem leaf, aloe, neem seed oil, eucalyptus, citronella, lemongrass, tea tree, lavender.",
    dose: "Shake well, spray on the coat. 32 fl oz.", sx: ["Bugs"] },
  { n: "NaturVet Fly Spray Concentrate", c: "Fly / Pest Control", v: "Does the Job", loc: "Grooming Bay",
    d: "Cedar oil and citronella concentrate.",
    dose: "Spray or brush on. 32 fl oz.",
    note: "May have helped Mickey when brushed on, but Avelin was still under attack 7/15/26.", sx: ["Bugs"] },

  // ---- Bathing
  { n: "Essential Equine Tea Tree Oil Shampoo", c: "Bathing", v: "Barn Favorite", loc: "Wash Bay", img: img(297),
    d: "Plant-based, sulfate-free conditioning shampoo with tea tree, aloe, and peppermint. Anti-microbial and mildly bug-repellent.",
    dose: "Wet, lather, rinse. Dilutes up to 20:1. Won't cause saddle slippage. 32 oz ~$23.99.", sx: ["Coat", "Mane/Tail"] },
  { n: "Vetrolin Bath (Farnam)", c: "Bathing", v: "Barn Favorite", loc: "Wash Bay", img: img(304),
    d: "Protein-enriched conditioning shampoo with vitamin E and PABA sunscreen. Fights dandruff, leaves a real shine.",
    dose: "2–4 oz into a bucket of water, lather in, sit 3 min, rinse. Keep out of eyes.", sx: ["Coat", "Mane/Tail"] },
  { n: "EQyss Micro-Tek Equine Shampoo", c: "Bathing", loc: "Wash Bay", img: img(299),
    d: "Medicated shampoo that soothes red, irritated skin on contact. Stops the scratching and rubbing.",
    dose: "Wet, lather over affected areas, let sit briefly, rinse. Safe on sensitive and broken skin. 32 oz ~$28.99.", sx: ["Itchy"] },
  { n: "EQyss Premier Equine Conditioner", c: "Bathing", v: "Does the Job", loc: "Wash Bay", img: img(300),
    d: "Detangling conditioner. Moisturizes dry, flaky skin with a non-slip finish.",
    dose: "Apply to wet, clean coat, mane, or tail. Work through and rinse. 16 oz ~$16.99.", sx: ["Itchy"] },
  { n: "EQyss Premier Equine Shampoo", c: "Bathing", loc: "Wash Bay",
    d: "Everyday companion shampoo to the Premier conditioner.", sx: ["Coat"] },
  { n: "It's A Fungus Amungus", c: "Bathing", v: "Proven", loc: "Wash Bay", img: img(295),
    d: "Leg and body wash that kills broad-spectrum fungal and bacterial skin infection. Rain rot, sweet itch, mud fever, scratches, ringworm.",
    dose: "Apply with a sponge, or add to the bath bucket. Safe daily. 16 oz ~$19.95.", sx: ["Rain Rot / Skin Infection"] },
  { n: "Quic Silver Whitening Shampoo", c: "Bathing", v: "Proven", loc: "Wash Bay", img: img(288),
    d: "Brightens white and grey coats, pulls yellow staining out.",
    dose: "Wet, lather onto white areas, let sit a few minutes, rinse thoroughly.", sx: ["Coat"] },
  { n: "Cowboy Magic Yellowout Whitening Shampoo", c: "Bathing",
    d: "Second whitening option for socks, blazes, and greys.", sx: ["Coat"] },
  { n: "Vetrolin White 'N Brite (Farnam)", c: "Bathing",
    d: "Whitening and brightening shampoo for show prep.", sx: ["Coat"] },
  { n: "Cowboy Magic Rosewater Conditioner", c: "Bathing", v: "Does the Job", loc: "Wash Bay", img: img(287),
    d: "Detangles and conditions mane and tail after washing, adds shine.",
    dose: "Apply to wet, clean mane or tail, work through, rinse or leave in.", sx: ["Coat"] },
  { n: "Mane 'n Tail Original Shampoo", c: "Bathing", loc: "Wash Bay", img: img(286),
    d: "Everyday shampoo for coat, mane, and tail.",
    dose: "Wet thoroughly, lather, rinse completely.", sx: ["Mane/Tail"] },
  { n: "Equiderma Neem Shampoo", c: "Bathing",
    d: "Neem-based shampoo for itchy, bug-bitten, funky skin.", sx: ["Itchy", "Rain Rot / Skin Infection", "Bugs"] },
  { n: "Vetericyn FoamCare Medicated Shampoo", c: "Bathing",
    d: "Foaming medicated shampoo. Fast to apply on a whole horse.", sx: ["Rain Rot / Skin Infection", "Itchy"] },
  { n: "Fly Bye! Plus Shampoo", c: "Bathing",
    d: "Bug-repellent shampoo companion to the Fly Bye! spray.", sx: ["Bugs"] },
  { n: "Essential Equine QuikClenz Foam-On Wash", c: "Bathing",
    d: "No-rinse foaming wash for cold days and quick cleanups.", sx: ["Coat"] },
  { n: "Smart Grooming Peppermint Splosh Wash", c: "Bathing",
    d: "Peppermint body wash. Cooling after hard work.", sx: ["Coat"] },

  // ---- Grooming
  { n: "EQyss Survivor Equine Detangler", c: "Grooming", v: "Proven", loc: "Grooming Bay", img: img(302),
    d: "Concentrated detangler. Non-greasy, non-sticky, won't attract dust.",
    dose: "Small amount on hands, run through mane or tail. One drop straight onto knots. 8 oz ~$16.10.",
    note: "Safe for all horses, ponies, pregnant mares, and foals.", sx: ["Mane/Tail"] },
  { n: "Canter Mane & Tail Conditioner", c: "Grooming", loc: "Grooming Bay", img: img(298),
    d: "Detangling conditioner spray. Oil-free shine, no residue, and the citronella helps repel flies.",
    dose: "Manes: fine mist, brush through. Tails: hold sections up, spray, brush. Wet or dry.",
    note: "Do not let it freeze.", sx: ["Mane/Tail"] },
  { n: "ShowSheen Detangler & Shine Spray", c: "Grooming", loc: "Grooming Bay", img: img(283),
    d: "Detangles mane and tail, adds shine, helps repel dirt.",
    dose: "Spray on clean, dry coat, mane, or tail. Avoid the saddle and girth area.", sx: ["Coat"] },
  { n: "EquinElite Silky Shine & Shield", c: "Grooming", loc: "Grooming Bay",
    d: "Alcohol-free herbal detangler for body, mane, and tail. Adds shine, prevents tangles.",
    dose: "Spray on, brush through. 32 fl oz.", sx: ["Coat"] },
  { n: "EquinElite Leave-In Conditioner", c: "Grooming",
    d: "Alcohol-free herbal leave-in for body, mane, and tail." },
  { n: "BioMane Detangler", c: "Grooming",
    d: "Coconut oil-infused detangler that preps hair for damage-free brushing." },
  { n: "BioMane Signature Conditioner", c: "Grooming",
    d: "Companion conditioner to the BioMane detangler.", sx: ["Mane/Tail"] },
  { n: "Equiderma Neem Conditioner", c: "Grooming",
    d: "Neem conditioner for coats and tails that need skin support too.", sx: ["Mane/Tail", "Coat"] },
  { n: "Effol Mane-Tail-Volumizer", c: "Grooming",
    d: "Care spray for a healthy, shiny mane and tail. Contains lemongrass oil." },
  { n: "EquiNature No Shock Anti-Static", c: "Grooming",
    d: "Aloe vera moisture spray. Kills static and dryness in winter." },
  { n: "Hair Moisturizer Concentrate (\"The Pink Stuff\")", c: "Grooming",
    d: "Lanolin-enriched concentrate for coats, manes, tails. Relieves dry skin, flaking, rubbing.",
    dose: "Mix 8 to 1, makes 1.125 gallons. Paraben free." },
  { n: "Smart Grooming Hot Cloth Wash", c: "Grooming",
    d: "Hot cloth wash for a deep clean without a full bath.", sx: ["Coat"] },
  { n: "Shiny Hiney Spray", c: "Grooming",
    d: "Tail and hindquarter shine spray.", sx: ["Coat"] },
  { n: "Winky Wash n Udder Stuff", c: "Grooming",
    d: "Sheath and udder cleaner. Somebody has to do it.", sx: ["Coat"] },
  { n: "Dr. Easy Eye Wipes (Dogs & Cats)", c: "Grooming",
    d: "Gentle pre-moistened wipes for eye discharge and gunk.", sx: ["Eye Injury / Infection"] },
  { n: "Noveha Dog Eye Wipes", c: "Grooming",
    d: "Second eye wipe option, kept with the first aid kit.", sx: ["Eye Injury / Infection"] },

  // ---- Supplements
  { n: "Pro-Elite Gut Biome", c: "Supplement", v: "Proven",
    d: "Concentrated pre/pro/postbiotics plus encapsulated zinc butyrate. HINDGUT-focused: repairs the cecum and colon lining.",
    dose: "Top-dress, ~45-day tub.",
    note: "Not currently in use, some horses hated the taste, but the product works. As of 7/18/26 recommended for everyone, not just loose-stool horses, and especially Cushing's horses who are already immune-suppressed. Different line from Empower Digestive Balance (foregut) — the two target opposite ends of the gut.",
    sx: ["Chronic Diarrhea"] },
  { n: "Platinum Performance Vitamin E Powder", c: "Supplement", v: "Proven", loc: "Supplement Shelf (Feed Room)", img: img(309),
    d: "Natural vitamin E antioxidant. Supports cell activity and protects cell membranes.",
    dose: "1 rounded scoop (6.4 g = 4,000 IU) twice daily for a 1,000 lb horse.", note: "From ~$73." },
  { n: "ProElite Sweat (Electrolytes)", c: "Supplement", v: "Proven", loc: "Supplement Shelf (Feed Room)", img: img(307),
    d: "Daily electrolyte pellet with no added sugar. Replaces what sweat takes.",
    dose: "Top-dress. 1 scoop maintenance, 1–4 for up to 1 hr work, 4–8 for 1–3 hrs, 8–14 for 3+ hrs." },
  { n: "SimpliFly Feed-Thru Fly Control", c: "Supplement", v: "Does the Job", loc: "Supplement Shelf (Feed Room)", img: img(306),
    d: "Feed-through control (LarvaStop / diflubenzuron) that stops house and stable fly larvae developing in manure. No organophosphates.",
    dose: "Top-dress on grain daily, 6.8 mg per 100 lbs body weight. Start early spring, run through fall." },
  { n: "AniMed Epsom Salt (Magnesium Sulfate)", c: "Supplement",
    d: "Bulk Epsom salt for hoof soaks and drawing poultices.", sx: ["Sore Muscles Joints", "Sore Hooves"] },
  { n: "Platinum Performance Bio-Sponge", c: "Supplement",
    d: "Di-tri-octahedral smectite. Binds toxins in acute diarrhea.", sx: ["Chronic Diarrhea"] },
  { n: "Probios Equine One Oral Gel", c: "Supplement",
    d: "Single-dose probiotic gel. Good after antibiotics, a stress move, or a gut upset.",
    sx: ["Chronic Diarrhea", "Colic"] },

  // ---- Feed
  { n: "Nutrena Empower Topline Balance", c: "Feed", v: "Barn Favorite",
    d: "Concentrated diet balancer with added chromium, amino acids, omega-3/6, and natural vitamin E. The baseline for every horse here.",
    dose: "40 lb bag, per label.",
    note: "First rung of the metabolic ladder. Add ProElite Topline Xtreme ON TOP of this (never instead) if a horse has visibly lost topline." },
  { n: "Nutrena SafeChoice Special Care", c: "Feed", v: "Barn Favorite",
    d: "Controlled-starch formula for easy keepers, with Digestive Shield prebiotics, probiotics, antioxidants.",
    dose: "50 lb bag, per label.",
    note: "Per Dr. Erin (7/18/26): reach for this once insulin stays elevated on lower-starch options alone. If a horse just needs calories or bulk, alfalfa or Timothy pellets are simpler and cheaper. This is for starch and sugar control specifically.",
    sx: ["Insulin Resistance"] },
  { n: "Standlee Alfalfa Pellets", c: "Feed", v: "Barn Favorite",
    d: "Premium sun-cured alfalfa forage pellets. Higher calorie and calcium than grass hay.",
    dose: "40 lb bag, fed as supplemental forage.",
    note: "NOT for insulin-dysregulated horses. Dahlia gets these specifically for weight gain." },
  { n: "Standlee Certified Timothy Pellets", c: "Feed", v: "Barn Favorite",
    d: "Low-NSC grass forage pellet, certified sun-cured and weed-seed free.",
    dose: "40 lb bag, fed as the forage portion.",
    note: "Interchangeable with Teff pellets for IR and Cushing's horses needing forage without added starch." },
  { n: "Standlee Teff Grass Pellets", c: "Feed", v: "Does the Job",
    d: "Naturally low-NSC grass forage pellet.",
    dose: "Fed as the forage portion.", note: "Interchangeable with Timothy pellets." },
  { n: "Nutrena Empower Digestive Balance", c: "Feed", v: "Proven",
    d: "Pelleted FOREGUT support. Built around maintaining normal gastric pH for ulcer-prone horses.",
    dose: "40 lb bag, top-dress per label.",
    note: "Hugo's current gut supplement. Use this over Gut Biome when the concern is gastric or ulcer-related. Not interchangeable with Pro-Elite Gut Biome without checking with the vet.",
    sx: ["Chronic Diarrhea"] },

  // ---- Dewormer
  { n: "Zimecterin Gold Dewormer", c: "Dewormer", v: "Barn Favorite", loc: "Med Shelf (Feed Room)", img: img(279),
    d: "Broad-spectrum: large and small strongyles, tapeworms, ascarids, bots.",
    dose: "Full syringe orally per body weight. Autumn/early winter after the first hard frost, and spring (May), per FEC and vet." },

  // ---- Retired
  { n: "InsulinWise", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Nutritional blend meant to promote a more normal insulin response.", sx: ["Insulin Resistance"] },
  { n: "Proleve Joint Supplement", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Oral joint support: glucosamine, chondroitin, Epicor postbiotic.", sx: ["Joint Swelling", "Sore Muscles Joints"] },
  { n: "Smart Metabo-Lean Pellets", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Weight-loss nutritional support for metabolic horses. Never a substitute for Thyro-L.", sx: ["Insulin Resistance"] },
  { n: "Smart Pituitary Senior", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Nutritional support for Cushing's horses, alongside Prascend rather than instead of it.", sx: ["Cushings"] },
  { n: "Smart Lamina Pellets", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Hoof support for delicate or weak hoof walls." },
  { n: "Smart & Simple Psyllium Pellets", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Psyllium fiber for monthly sand clearing." },
  { n: "Smart Bug-Off Pellets", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Feed-through fly control. Tried as an alternative to Formula 707 Multi-Fly." },
  { n: "ProElite Topline Xtreme", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Extra topline and muscling support, layered on top of Empower Topline Balance." },
  { n: "Mare Magic", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Raspberry leaf herbal for steadying mood through heat cycles. Don't use with SmartMare Harmony." },
  { n: "SmartMare Harmony", c: "Supplement", v: "Underwhelming", retired: true,
    d: "Mood support through heat cycles. Alternative to Mare Magic, not a companion." },
  { n: "Nutrena SafeChoice Senior (with molasses)", c: "Feed", v: "Does the Job", retired: true,
    d: "Senior complete feed for horses WITHOUT insulin or metabolic concerns.",
    note: "The molasses makes this wrong for any Cushing's or IR horse. Switch to Molasses-Free or Special Care." },
  { n: "Nutrena SafeChoice Senior Molasses-Free", c: "Feed", v: "Does the Job", retired: true,
    d: "Senior complete feed for Cushing's and IR horses with poor dentition.",
    dose: "Start 1 lb AM + 1 lb PM, safely up to ~16 lb/day.",
    note: "Was Linka and Tammy's feed. Step up to Special Care if insulin stays high.", sx: ["Insulin Resistance"] },
];

// ---------------------------------------------------------------- symptoms
export const SYMPTOMS = [
  { n: "Colic", blurb: "Pawing, rolling, looking at the flank, off feed, no gut sounds.",
    vet: "CALL THE VET. Banamine can mask signs, so call before or as you give it. Walk the horse, pull all feed and hay, note the last manure and water." },
  { n: "Heat Stress", blurb: "Heavy sustained breathing, no sweat or drenched, wobbly, temp over 103°F.",
    vet: "CALL THE VET. Get the horse in shade, cold hose the big vessels (neck, chest, inside legs), scrape and repeat. Do not stop hosing while you wait." },
  { n: "EPM", blurb: "Asymmetric weakness, stumbling, muscle wasting, odd head carriage.",
    vet: "CALL THE VET. Neurologic signs need a real exam and a titer before treating. Do not start a course on a hunch." },
  { n: "Itchy",
    blurb: "Rubbing, tail chewing, hives, bald patches. Peak season is spring through fall.",
    ladder: [
      { tier: 1, items: ["Cetirizine Hydrochloride 10mg", "Hydroxyzine Hydrochloride 50mg", "EquiShield IBH Spray", "EquiShield IR (Itch Relief) Spray"] },
      { tier: 2, items: ["EQyss Micro-Tek Equine Spray", "Coat Defense", "EQyss Micro-Tek Equine Shampoo", "EquiShield IR (Itch Relief) Shampoo"] },
      { tier: 3, items: ["Dex (Dexamethasone Tablets)", "Dex (Dexamethasone Injectable)", "Vetalog Parenteral (Triamcinolone Acetonide)"] },
    ],
    rule: "Start at the first sign, not once they're miserable. Dr. Erin's whole point: antihistamines and topicals first so we're not putting systemic steroids through the herd." },
  { n: "Joint Swelling", blurb: "Filled joint, warm to the touch, short-strided out of the paddock.",
    ladder: [
      { tier: 1, items: ["Bigeloil Liquid Gel", "Liniment (Farnam Vetrolin)", "Bute Paste (Phenylbutazone)", "Equioxx (Firocoxib) Tablets"] },
      { tier: 2, items: ["Adequan (PSGAG)", "Legend (Hyaluronic Acid)", "Zycosan (Pentosan Polysulfate)"] },
    ],
    rule: "Adequan plus monthly Legend is the base program. Equioxx is a flare-up add-on, not the daily plan." },
  { n: "Sore Muscles Joints", blurb: "Tight over the back, cranky to groom, stiff for the first ten minutes.",
    ladder: [
      { tier: 1, items: ["Liniment (Farnam Vetrolin)", "Bigeloil Liquid Gel", "Sore No-More Performance Ultra Poultice", "Durvet Epsom Salt Poultice (Flowable Gel)"] },
      { tier: 2, items: ["Equioxx (Firocoxib) Tablets", "Adequan (PSGAG)", "Legend (Hyaluronic Acid)"] },
    ] },
  { n: "Insulin Resistance", blurb: "Cresty neck, fat pads over the tailhead and shoulders, footy on hard ground.",
    ladder: [
      { tier: 1, items: ["Nutrena Empower Topline Balance", "Nutrena SafeChoice Special Care", "Standlee Certified Timothy Pellets", "Standlee Teff Grass Pellets"] },
      { tier: 2, items: ["Thyro-L (Levothyroxine Sodium)"] },
      { tier: 3, items: ["Ertugliflozin (SGLT2 Inhibitor)"] },
    ],
    rule: "Diet and exercise → low-NSC feed → Thyro-L → ertugliflozin. Insulin over 200 means laminitis is imminent. Trigger for the last rung is non-response, not a calendar date." },
  { n: "Cushings", blurb: "Long curly coat that won't shed, patchy sweating, recurring infections, muscle loss.",
    ladder: [
      { tier: 1, items: ["Prascend (Pergolide) Tablets"] },
      { tier: 2, items: ["IM Pergolide (Injectable)", "Cabergoline Injectable (BET Pharm)"] },
    ],
    rule: "Cushing's horses are immune-suppressed. Gut and skin support matters more for them, not less." },
  { n: "Minor cut or scrape", blurb: "Clean it, look at it in good light, decide whether it needs a vet before you cover it." },
  { n: "Swelling From Kick", blurb: "Hot, localized, appeared overnight. Check for a puncture before you poultice." },
  { n: "Swelling From Bug Bites", blurb: "Soft, diffuse, usually along the belly, chest, or sheath." },
  { n: "Tiny Bumps From Bug Bites", blurb: "Crops of small welts under the saddle area and along the neck." },
  { n: "Sore Hooves", blurb: "Short over gravel, pulse in the digital artery, shifting weight. Take it seriously." },
  { n: "Hoof Abscess", blurb: "Suddenly three-legged lame with heat and a bounding digital pulse. Soak, pack, and wait for it to pop." },
  { n: "Thrush", blurb: "Black, smelly discharge in the clefts of the frog. Mud season problem." },
  { n: "Rain Rot / Skin Infection", blurb: "Crusty scabs along the back and rump that lift with a plug of hair." },
  { n: "Chronic Diarrhea", blurb: "Loose stool that won't firm up. Hindgut problem, not a foregut one." },
  { n: "Eye Injury / Infection", blurb: "Squinting, tearing, swelling. Eyes go bad fast; when in doubt, call." },
  { n: "Bugs", blurb: "General fly, gnat, mosquito, and tick pressure. Forest Lake summers are relentless." },
  { n: "Coat", blurb: "Dull, sun-bleached, or stained. Bathing and grooming, not medicine." },
  { n: "Mane/Tail", blurb: "Thin, broken, rubbed out. Growth takes months of consistency." },
  { n: "Respiratory Allergies", blurb: "Cough at the start of work, nasal discharge, higher resting breaths." },
  { n: "Choke", blurb: "Feed and saliva back out the nose, repeated stretching and coughing. Pull all feed and call." },
];

export const TIERS = {
  1: { label: "Try First", color: "#3F6B45" },
  2: { label: "Step 2", color: "#8F6606" },
  3: { label: "Last Resort", color: "#A31E22" },
};

// Field values come off the ClickUp labels field; these are the human versions.
const LABEL = {
  "Sore Muscles Joints": "Sore Muscles & Joints",
  "Insulin Resistance": "Insulin Resistance / Metabolic",
  "Cushings": "Cushing's (PPID)",
  "EPM": "EPM / Neurologic Signs",
  "Chronic Diarrhea": "Chronic Diarrhea / Gut",
  "Minor cut or scrape": "Minor Cut or Scrape",
  "Swelling From Kick": "Swelling: From a Kick",
  "Swelling From Bug Bites": "Swelling: From Bug Bites",
  "Tiny Bumps From Bug Bites": "Tiny Bumps: From Bug Bites",
  "Bugs": "Bug Pressure",
  "Coat": "Dull or Stained Coat",
  "Mane/Tail": "Mane & Tail",
  "Itchy": "Itchy / Rubbing",
  "Sore Hooves": "Sore or Footy Hooves",
  "Colic": "Colic",
};
export const sxLabel = (n) => LABEL[n] || n;

// ---------------------------------------------------------------- paddocks
export const HORSE_COLOR = {
  Mickey: "#2E6E8E", Avelin: "#D2761B", Dahlia: "#B5537A", Qu: "#7A8288",
  Stendahl: "#2B2F33", Ulyssa: "#D8398A", Hugo: "#6B4A9C", Linka: "#3F6B45", Tammy: "#7A5230",
};

export const PADDOCKS = [
  { id: 1, name: "Paddock 1", corner: "NW", horses: ["Qu"], note: "Solo. New-ish here and still finding his feet." },
  { id: 2, name: "Paddock 2", corner: "NE", horses: ["Mickey", "Avelin", "Dahlia"] },
  { id: 3, name: "Paddock 3", corner: "SE", horses: ["Hugo", "Linka", "Tammy"] },
  { id: 4, name: "Paddock 4", corner: "SW", horses: ["Stendahl", "Ulyssa"] },
];

export const ZONES = [
  { name: "Track 1", type: "track" },
  { name: "Track 2", type: "track" },
  { name: "Track 3", type: "track" },
  { name: "Obstacle Pasture", type: "pasture" },
  { name: "Hill Pasture", type: "pasture" },
  { name: "Pond Pasture", type: "pasture" },
  { name: "Outdoor Arena", type: "arena" },
  { name: "Round Pen", type: "arena" },
  { name: "Stall 1", type: "stall" },
  { name: "Stall 2", type: "stall" },
  { name: "Stall 3", type: "stall" },
  { name: "Stall 4", type: "stall" },
  { name: "Porch N", type: "porch" },
  { name: "Porch S", type: "porch" },
];

export const PADDOCK_META = {
  effective: "Effective Feb 1, 2026",
  extras: [
    "Tracks, pastures, and arenas are shared rotational turnout, not permanent assignments.",
    "Hugo and Dahlia do not go out together. Aug 21, 2026: pinned ears, galloping the fence, kicking through it.",
  ],
};

export const CONTACTS = [
  { role: "Primary vet", name: "Dr. Jon Engstrom", detail: "Stillwater Equine Vet Clinic" },
  { role: "Consults", name: "Dr. Erin Wilson", detail: "Metabolic, skin, and gut protocols" },
  { role: "Farrier", name: "Krystyna & Maria Eischens", detail: "June 2026 onward" },
  { role: "Chiro / bodywork", name: "Dr. Hal Brown", detail: "" },
];

export const SX_EMOJI = {
  "Colic": "🚨",
  "Heat Stress": "🥵",
  "EPM": "🐴",
  "Itchy": "😣",
  "Joint Swelling": "🦴",
  "Sore Muscles Joints": "💪",
  "Insulin Resistance": "🩸",
  "Cushings": "🧬",
  "Minor cut or scrape": "🔪",
  "Swelling From Kick": "🐎",
  "Swelling From Bug Bites": "🫧",
  "Tiny Bumps From Bug Bites": "👆",
  "Sore Hooves": "🐾",
  "Hoof Abscess": "🔥",
  "Thrush": "🦶",
  "Rain Rot / Skin Infection": "🐾",
  "Chronic Diarrhea": "💩",
  "Eye Injury / Infection": "👁️",
  "Bugs": "🐛",
  "Coat": "✨",
  "Mane/Tail": "💇",
  "Respiratory Allergies": "🌬️",
  "Choke": "⚠️",
};

export const CAT_EMOJI = {
  "First Aid": "🩹",
  "Wound Care": "🩹",
  "Medication": "💊",
  "Muscle & Joint": "💪",
  "Skin / Coat": "🧴",
  "Hoof Care": "🦶",
  "Fly / Pest Control": "🪰",
  "Bathing": "🚿",
  "Grooming": "✨",
  "Supplement": "🥄",
  "Feed": "🌾",
  "Dewormer": "🪱",
};
